create table if not exists public.leads (
  slug text primary key,
  nome text,
  nicho text,
  cidade text,
  nota double precision,
  avaliacoes bigint,
  email text,
  telefone text,
  whatsapp text,
  "siteAntigo" text,
  motivo text,
  status text default 'novo',
  "urlNova" text,
  "dataProposta" text,
  valor double precision,
  obs text,
  "contratoStatus" text default 'pendente',
  "contratoEm" text,
  manutencao double precision,
  pago bigint default 0,
  "docCliente" text,
  "endCliente" text,
  atualizado text,
  "placeId" text,
  "opportunityType" text,
  "opportunityScore" bigint,
  "classificationEvidence" text,
  "mainRisk" text,
  "factualContent" text,
  "imageryLevel" text,
  "socialUrls" text,
  "mapsUrl" text,
  "runId" bigint,
  "criadoEm" text,
  country text,
  locale text,
  language text,
  "phoneCountryCode" text,
  "websiteStatus" text default 'existing_weak',
  "siteMode" text default 'redesign',
  currency text,
  "marketTier" text
  ,candidate_url text
  ,live_url text
  ,proposal_url text
);

create table if not exists public.outreach_history (
  id bigint generated by default as identity primary key,
  slug text not null,
  canal text not null,
  destino text,
  tipo text default 'proposta',
  mensagem text,
  "urlProposta" text,
  "mensagemId" text,
  status text default 'enviado',
  "criadoEm" text
);

create index if not exists outreach_history_slug_idx on public.outreach_history (slug);

alter table public.leads enable row level security;
alter table public.leads force row level security;
alter table public.outreach_history enable row level security;
alter table public.outreach_history force row level security;

revoke all on table public.leads from anon, authenticated;
revoke all on table public.outreach_history from anon, authenticated;
grant all on table public.leads to service_role;
grant all on table public.outreach_history to service_role;
grant usage, select on all sequences in schema public to service_role;
