#!/usr/bin/env python3
"""Post-process a generated Prospector editor so brand/logo media wins over link navigation.

This is intentionally small and source-preserving: it patches only the embedded
editor runtime generated by ``prospector-de-sites/create_editor.py``. The public
site HTML is not modified.
"""

from __future__ import annotations

import pathlib

PATCH_MARKER = "/* PROSPECTOR-BRAND-MEDIA-PATCH v1 */"


def patch_editor(path: pathlib.Path) -> bool:
    html = path.read_text(encoding="utf-8")
    if PATCH_MARKER in html:
        return False

    replacements = [
        (
            "function imgSource(el){return el.tagName==='IMG'?(el.currentSrc||el.getAttribute('src')||''):(el.getAttribute('data-pe-bg-src')||'')}\n"
            "function peersForImage(){\n"
            "  if(state.fieldKey)return $$('[data-pe-field=\"'+CSS.escape(state.fieldKey)+'\"]');\n"
            "  return $$(IMAGE_SELECTOR).filter(function(el){return imgSource(el)===state.originalSrc});\n"
            "}\n"
            "function openImage(el){\n"
            "  clearSelection();state.selected=el;state.kind='image';state.originalSrc=imgSource(el);state.fieldKey=el.getAttribute('data-pe-field')||'';\n"
            "  el.classList.add('pe-selected');\n"
            "  $('#pe-panel-title').textContent=el.tagName==='IMG'?'Imagem':'Imagem de fundo';\n"
            "  actionFields.classList.add('pe-hidden');imageFields.classList.remove('pe-hidden');\n"
            "  imageSrc.value=state.originalSrc;imageAlt.value=el.tagName==='IMG'?(el.getAttribute('alt')||''):(el.getAttribute('aria-label')||'');\n"
            "  imageSync.checked=false;panel.classList.add('pe-open');\n"
            "}\n",
            "function imgSource(el){return el.tagName==='IMG'?(el.currentSrc||el.getAttribute('src')||''):(el.getAttribute('data-pe-bg-src')||'')}\n"
            + PATCH_MARKER
            + "\nfunction looksLikeBrandLogo(el){\n"
            "  if(!el||el.tagName!=='IMG')return false;\n"
            "  var a=el.closest('a[href],a[data-href],[data-pe-action]');\n"
            "  var context=[el.getAttribute('src')||'',el.getAttribute('alt')||'',el.id||'',el.className||'',a?(a.id||''):'',a?(a.className||''):''].join(' ').toLowerCase();\n"
            "  if(/(^|[\\s_\\-\\/.])(logo|logotipo|brand|marca)([\\s_\\-\\/.]|$)/i.test(context))return true;\n"
            "  var shell=el.closest('header,nav,footer,[class*=\"logo\" i],[class*=\"brand\" i],[id*=\"logo\" i],[id*=\"brand\" i]');\n"
            "  if(!shell||!a)return false;\n"
            "  var h=actionHref(a);\n"
            "  try{var u=new URL(h||'/',location.href);return u.origin===location.origin&&(u.pathname==='/'||/\\/(?:index\\.html?)?$/i.test(u.pathname))}catch(e){return h==='/'||h==='./'||/^index\\.html?$/i.test(h)}\n"
            "}\n"
            "function inferImageField(el){\n"
            "  var explicit=el.getAttribute('data-pe-field');\n"
            "  if(explicit)return explicit;\n"
            "  if(looksLikeBrandLogo(el))return'brand.logo';\n"
            "  return'';\n"
            "}\n"
            "function peersForImage(){\n"
            "  if(state.fieldKey)return $$(IMAGE_SELECTOR).filter(function(el){return inferImageField(el)===state.fieldKey});\n"
            "  return $$(IMAGE_SELECTOR).filter(function(el){return imgSource(el)===state.originalSrc});\n"
            "}\n"
            "function openImage(el){\n"
            "  clearSelection();state.selected=el;state.kind='image';state.originalSrc=imgSource(el);state.fieldKey=inferImageField(el);\n"
            "  el.classList.add('pe-selected');\n"
            "  $('#pe-panel-title').textContent=state.fieldKey==='brand.logo'?'Logo / marca':(el.tagName==='IMG'?'Imagem':'Imagem de fundo');\n"
            "  actionFields.classList.add('pe-hidden');imageFields.classList.remove('pe-hidden');\n"
            "  imageSrc.value=state.originalSrc;imageAlt.value=el.tagName==='IMG'?(el.getAttribute('alt')||''):(el.getAttribute('aria-label')||'');\n"
            "  imageSync.checked=!!state.fieldKey;panel.classList.add('pe-open');\n"
            "}\n",
        ),
        (
            "/* Capture-phase delegation is intentional: it intercepts CTA/social clicks before\n"
            "   page-specific navigation handlers, SVG child handlers, or stopPropagation logic. */\n"
            "document.addEventListener('click',function(e){\n"
            "  if(state.mode!=='edit'||isUI(e.target))return;\n"
            "  var action=closestAction(e.target);\n"
            "  if(action){\n"
            "    e.preventDefault();e.stopPropagation();\n"
            "    if(e.stopImmediatePropagation)e.stopImmediatePropagation();\n"
            "    openAction(action);return;\n"
            "  }\n"
            "  var image=closestImage(e.target);\n"
            "  if(image){\n"
            "    e.preventDefault();e.stopPropagation();\n"
            "    if(e.stopImmediatePropagation)e.stopImmediatePropagation();\n"
            "    openImage(image);\n"
            "  }\n"
            "},true);\n\n"
            "document.addEventListener('pointerover',function(e){\n"
            "  if(state.mode!=='edit'||isUI(e.target))return;\n"
            "  var action=closestAction(e.target),image=action?null:closestImage(e.target);\n"
            "  if(action)action.classList.add('pe-hover');else if(image)image.classList.add('pe-hover');\n"
            "},true);\n"
            "document.addEventListener('pointerout',function(e){\n"
            "  var action=closestAction(e.target),image=action?null:closestImage(e.target);\n"
            "  if(action)action.classList.remove('pe-hover');else if(image)image.classList.remove('pe-hover');\n"
            "},true);\n",
            "/* Capture-phase delegation is intentional. Media gets first priority when the\n"
            "   pointer is directly on an editable image, even when that image lives inside a link.\n"
            "   This makes header/footer logos replaceable instead of misclassifying them as actions. */\n"
            "document.addEventListener('click',function(e){\n"
            "  if(state.mode!=='edit'||isUI(e.target))return;\n"
            "  var image=closestImage(e.target);\n"
            "  if(image){\n"
            "    e.preventDefault();e.stopPropagation();\n"
            "    if(e.stopImmediatePropagation)e.stopImmediatePropagation();\n"
            "    openImage(image);return;\n"
            "  }\n"
            "  var action=closestAction(e.target);\n"
            "  if(action){\n"
            "    e.preventDefault();e.stopPropagation();\n"
            "    if(e.stopImmediatePropagation)e.stopImmediatePropagation();\n"
            "    openAction(action);\n"
            "  }\n"
            "},true);\n\n"
            "document.addEventListener('pointerover',function(e){\n"
            "  if(state.mode!=='edit'||isUI(e.target))return;\n"
            "  var image=closestImage(e.target),action=image?null:closestAction(e.target);\n"
            "  if(image)image.classList.add('pe-hover');else if(action)action.classList.add('pe-hover');\n"
            "},true);\n"
            "document.addEventListener('pointerout',function(e){\n"
            "  var image=closestImage(e.target),action=image?null:closestAction(e.target);\n"
            "  if(image)image.classList.remove('pe-hover');else if(action)action.classList.remove('pe-hover');\n"
            "},true);\n",
        ),
        (
            "function applyImageTo(el,src,alt){\n"
            "  if(el.tagName==='IMG'){el.setAttribute('src',src);el.removeAttribute('srcset');if(alt!==undefined)el.setAttribute('alt',alt)}\n"
            "  else{el.setAttribute('data-pe-bg-src',src);el.style.backgroundImage='url(\"'+src.replace(/\"/g,'%22')+'\")';if(alt!==undefined&&alt)el.setAttribute('aria-label',alt)}\n"
            "}\n",
            "function applyImageTo(el,src,alt){\n"
            "  if(el.tagName==='IMG'){\n"
            "    el.setAttribute('src',src);el.removeAttribute('srcset');if(alt!==undefined)el.setAttribute('alt',alt);\n"
            "    var picture=el.closest('picture');if(picture){$$('source',picture).forEach(function(s){s.setAttribute('srcset',src)})}\n"
            "  }else{el.setAttribute('data-pe-bg-src',src);el.style.backgroundImage='url(\"'+src.replace(/\"/g,'%22')+'\")';if(alt!==undefined&&alt)el.setAttribute('aria-label',alt)}\n"
            "}\n",
        ),
    ]

    for old, new in replacements:
        if old not in html:
            raise RuntimeError(
                f"Editor runtime signature changed; brand-media patch could not be applied safely to {path}."
            )
        html = html.replace(old, new, 1)

    path.write_text(html, encoding="utf-8")
    return True


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Patch generated editor for editable brand/logo media")
    parser.add_argument("editor_html")
    args = parser.parse_args()
    target = pathlib.Path(args.editor_html)
    changed = patch_editor(target)
    print(f"Brand-media editor patch {'applied' if changed else 'already present'}: {target}")
